name: Deployment

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile -t lmermod-website
      
    - name: Restart service
      run: systemctl restart lmermod-website.service
