name: Docker

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  push:
    branches: [ "main" ]


jobs:
  build:

    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Build docker
        run: docker build . -t lmermod-website

      - name: Restart website
        run: ~/actions-runner/lmermod-website/restart.sh